### ISSUE TITLE
places files and directories in wrong paths for patches

### ISSUE THREAD

**Issue by TheRadziu** [hippie68/ftpdump#4] opened 2021-12-13 21:55 UTC
Your script works awesome for base games, but for patches it throws most stuff in the root of the CUSAXXXXX-patch directory, for example Marvel's Guardians of the galaxy 1.05 patch:
![image](https://user-images.githubusercontent.com/7728545/145894588-a8ad343b-770e-4666-9139-216f5fa29611.png)
the randomly named res files should be in `/CUSAXXXXX-patch/runtime/` directory, about and changeinfo should be in `CUSAXXXX-patch/sce_sys` which ftp confirms:
![image](https://user-images.githubusercontent.com/7728545/145894767-77786010-9af9-4565-97fa-3c0d70645d02.png)

Same with KH: Melody of Memory:
![image](https://user-images.githubusercontent.com/7728545/145894906-7364a214-fc46-4a40-af78-1c88b4e46590.png)
`about`, `changeinfo`, `trophy` should be in `CUSAXXXXX-patch/sce_sys`
`Metadata`, `Modules`, `Plugins`, `StreamingAssets`, `globalgamemanagers` and `globalgamemanagers.assets` should be in `/CUSAXXXXX-patch/Media` which doesnt exist at all

~~usage of `--use-pfs ` might be workaround for this issue, but i havent tested it yet.~~
`--use-pfs` generates proper directory layout but majority of files are 0kb in size, also eboot and other modules are just missing.

**Comment by ArcziPS4** [comment] 2021-12-13 21:57
Same with Nier Replicant
![image](https://user-images.githubusercontent.com/94761108/145895321-466dd746-5627-4b11-989e-f60f743ff8a8.png)

**Comment by hippie68** [comment] 2021-12-13 22:51
It could help to run the script with options --verbose and/or --debug, to see what's happening to the paths. I am not on 9.00 and can't test those games. Does it happen with any game?

**Comment by TheRadziu** [comment] 2021-12-13 23:10
> It could help to run the script with options --verbose and/or --debug, to see what's happening to the paths. I am not on 9.00 and can't test those games. Does it happen with any game?

so far happened on three we tested and listed. below are --verbose and --debug logs for KH Melody of memory 1.04 patch since its smallest in size:
[verbose_log.txt](https://github.com/hippie68/ftpdump/files/7707494/verbose_log.txt)
[debug_log.txt](https://github.com/hippie68/ftpdump/files/7707502/debug_log.txt)

**Comment by hippie68** [comment] 2021-12-13 23:54
Appears to be a bug in the path. It is important to specify HOSTNAME or IP_ADDRESS without trailing slashes.

For example:

    ftpdump 192.168.1.2:2121 -p

Instead of:

    ftpdump 192.168.1.2:2121/ -p

I will fix this in a new update. In the meantime, you should be able to dump by not adding slashes. There might be more to it, but if you did run a separate command for patches that had a trailing slash, I think this should be the fix.

The optional PFS extraction might be broken for now.

**Comment by TheRadziu** [comment] 2021-12-14 00:05
i have ip & port set in script itself, without any additional slashes, used `ftpdump IP:PORT -p` earlier too and resulted in exact same issue

**Comment by hippie68** [comment] 2021-12-14 09:02
For reasons unknown the script cuts more directories than it should. I could not reproduce the bug on my machines, however I made some changes which could help. Please run the attached script with option --debug and tell me if the bug has been fixed.

It should say "DEBUG: Dumping directory "xxx", cutting 4 directories." when starting to dump a patch. I would expect the bug to happen if the number is 5, which it shouldn't be. But perhaps it is fixed now.

[ftpdump.zip](https://github.com/hippie68/ftpdump/files/7710164/ftpdump.zip)

**Closed** 2021-12-14 09:41 UTC

**Comment by hippie68** [comment] 2021-12-20 08:11
PFS extraction should now be fixed, thank you for reporting.
