### ISSUE TITLE
Cant dump Shadow of the TopRaider Patch 2.01

### ISSUE THREAD

**Issue by falcon040** [hippie68/ftpdump#11] opened 2021-12-26 05:56 UTC
You search for a  patch here:
 "$root/mnt/sandbox/pfsmnt/$title_id-patch0/" > /dev/null

But there is no patch there...

I can find:
ftp://192.168.2.4:2121/mnt/sandbox/pfsmnt/CUSA10872-app0
ftp://192.168.2.4:2121/mnt/sandbox/pfsmnt/CUSA10872-app0-nest
ftp://192.168.2.4:2121/mnt/sandbox/pfsmnt/CUSA10872-app0-patch0-union

This is the content of CUSA10872-app0-patch0-union:

ftp://192.168.2.4:2121/mnt/sandbox/pfsmnt/CUSA10872-app0-patch0-union/movies
ftp://192.168.2.4:2121/mnt/sandbox/pfsmnt/CUSA10872-app0-patch0-union/sce_module
ftp://192.168.2.4:2121/mnt/sandbox/pfsmnt/CUSA10872-app0-patch0-union/sce_sys
ftp://192.168.2.4:2121/mnt/sandbox/pfsmnt/CUSA10872-app0-patch0-union/bigfile.000.nfo
ftp://192.168.2.4:2121/mnt/sandbox/pfsmnt/CUSA10872-app0-patch0-union/bigfile.000.tiger
ftp://192.168.2.4:2121/mnt/sandbox/pfsmnt/CUSA10872-app0-patch0-union/bigfile.001.tiger
ftp://192.168.2.4:2121/mnt/sandbox/pfsmnt/CUSA10872-app0-patch0-union/bigfile.002.tiger
ftp://192.168.2.4:2121/mnt/sandbox/pfsmnt/CUSA10872-app0-patch0-union/bigfile.003.tiger
ftp://192.168.2.4:2121/mnt/sandbox/pfsmnt/CUSA10872-app0-patch0-union/bigfile.remaster.003.000.nfo
ftp://192.168.2.4:2121/mnt/sandbox/pfsmnt/CUSA10872-app0-patch0-union/bigfile.remaster.003.000.tiger
ftp://192.168.2.4:2121/mnt/sandbox/pfsmnt/CUSA10872-app0-patch0-union/bigfile.remaster.003.001.tiger
ftp://192.168.2.4:2121/mnt/sandbox/pfsmnt/CUSA10872-app0-patch0-union/bigfile.remaster.003.002.tiger
ftp://192.168.2.4:2121/mnt/sandbox/pfsmnt/CUSA10872-app0-patch0-union/bigfile.remaster.003.003.tiger
ftp://192.168.2.4:2121/mnt/sandbox/pfsmnt/CUSA10872-app0-patch0-union/bigfile.remaster.003.004.tiger
ftp://192.168.2.4:2121/mnt/sandbox/pfsmnt/CUSA10872-app0-patch0-union/bigfile.remaster.003.005.tiger
ftp://192.168.2.4:2121/mnt/sandbox/pfsmnt/CUSA10872-app0-patch0-union/bigfile.remaster.003.006.tiger
ftp://192.168.2.4:2121/mnt/sandbox/pfsmnt/CUSA10872-app0-patch0-union/bigfile.remaster.003.007.tiger
ftp://192.168.2.4:2121/mnt/sandbox/pfsmnt/CUSA10872-app0-patch0-union/bigfile.remaster.003_alltxt_english_allplt.000.tiger
ftp://192.168.2.4:2121/mnt/sandbox/pfsmnt/CUSA10872-app0-patch0-union/bigfile.remaster.003_alltxt_french_allplt.000.tiger
ftp://192.168.2.4:2121/mnt/sandbox/pfsmnt/CUSA10872-app0-patch0-union/bigfile.remaster.003_alltxt_german_allplt.000.tiger
ftp://192.168.2.4:2121/mnt/sandbox/pfsmnt/CUSA10872-app0-patch0-union/bigfile.remaster.003_alltxt_iberspanish_allplt.000.tiger
ftp://192.168.2.4:2121/mnt/sandbox/pfsmnt/CUSA10872-app0-patch0-union/bigfile.remaster.003_alltxt_italian_allplt.000.tiger
ftp://192.168.2.4:2121/mnt/sandbox/pfsmnt/CUSA10872-app0-patch0-union/bigfile.remaster.003_alltxt_latamspanish_allplt.000.tiger
ftp://192.168.2.4:2121/mnt/sandbox/pfsmnt/CUSA10872-app0-patch0-union/bigfile.remaster.003_alltxt_polish_allplt.000.tiger
ftp://192.168.2.4:2121/mnt/sandbox/pfsmnt/CUSA10872-app0-patch0-union/bigfile.remaster.003_alltxt_portuguese_allplt.000.tiger
ftp://192.168.2.4:2121/mnt/sandbox/pfsmnt/CUSA10872-app0-patch0-union/bigfile.remaster.003_alltxt_russian_allplt.000.tiger
ftp://192.168.2.4:2121/mnt/sandbox/pfsmnt/CUSA10872-app0-patch0-union/bigfile.remaster.003_english_allvo_allplt.000.tiger
ftp://192.168.2.4:2121/mnt/sandbox/pfsmnt/CUSA10872-app0-patch0-union/bigfile.remaster.003_french_allvo_allplt.000.tiger
ftp://192.168.2.4:2121/mnt/sandbox/pfsmnt/CUSA10872-app0-patch0-union/bigfile.remaster.003_german_allvo_allplt.000.tiger
ftp://192.168.2.4:2121/mnt/sandbox/pfsmnt/CUSA10872-app0-patch0-union/bigfile.remaster.003_iberspanish_allvo_allplt.000.tiger
ftp://192.168.2.4:2121/mnt/sandbox/pfsmnt/CUSA10872-app0-patch0-union/bigfile.remaster.003_italian_allvo_allplt.000.tiger
ftp://192.168.2.4:2121/mnt/sandbox/pfsmnt/CUSA10872-app0-patch0-union/bigfile.remaster.003_latamspanish_allvo_allplt.000.tiger
ftp://192.168.2.4:2121/mnt/sandbox/pfsmnt/CUSA10872-app0-patch0-union/bigfile.remaster.003_polish_allvo_allplt.000.tiger
ftp://192.168.2.4:2121/mnt/sandbox/pfsmnt/CUSA10872-app0-patch0-union/bigfile.remaster.003_portuguese_allvo_allplt.000.tiger
ftp://192.168.2.4:2121/mnt/sandbox/pfsmnt/CUSA10872-app0-patch0-union/bigfile.remaster.003_russian_allvo_allplt.000.tiger
ftp://192.168.2.4:2121/mnt/sandbox/pfsmnt/CUSA10872-app0-patch0-union/bigfile.remaster.patch.002.000.nfo
ftp://192.168.2.4:2121/mnt/sandbox/pfsmnt/CUSA10872-app0-patch0-union/bigfile.remaster.patch.002.000.tiger
ftp://192.168.2.4:2121/mnt/sandbox/pfsmnt/CUSA10872-app0-patch0-union/bigfile.remaster.patch.002_alltxt_english_allplt.000.tiger
ftp://192.168.2.4:2121/mnt/sandbox/pfsmnt/CUSA10872-app0-patch0-union/bigfile.remaster.patch.002_alltxt_french_allplt.000.tiger
ftp://192.168.2.4:2121/mnt/sandbox/pfsmnt/CUSA10872-app0-patch0-union/bigfile.remaster.patch.002_alltxt_german_allplt.000.tiger
ftp://192.168.2.4:2121/mnt/sandbox/pfsmnt/CUSA10872-app0-patch0-union/bigfile.remaster.patch.002_alltxt_iberspanish_allplt.000.tiger
ftp://192.168.2.4:2121/mnt/sandbox/pfsmnt/CUSA10872-app0-patch0-union/bigfile.remaster.patch.002_alltxt_italian_allplt.000.tiger
ftp://192.168.2.4:2121/mnt/sandbox/pfsmnt/CUSA10872-app0-patch0-union/bigfile.remaster.patch.002_alltxt_latamspanish_allplt.000.tiger
ftp://192.168.2.4:2121/mnt/sandbox/pfsmnt/CUSA10872-app0-patch0-union/bigfile.remaster.patch.002_alltxt_polish_allplt.000.tiger
ftp://192.168.2.4:2121/mnt/sandbox/pfsmnt/CUSA10872-app0-patch0-union/bigfile.remaster.patch.002_alltxt_portuguese_allplt.000.tiger
ftp://192.168.2.4:2121/mnt/sandbox/pfsmnt/CUSA10872-app0-patch0-union/bigfile.remaster.patch.002_alltxt_russian_allplt.000.tiger
ftp://192.168.2.4:2121/mnt/sandbox/pfsmnt/CUSA10872-app0-patch0-union/bigfile.remaster.patch.002_english_allvo_allplt.000.tiger
ftp://192.168.2.4:2121/mnt/sandbox/pfsmnt/CUSA10872-app0-patch0-union/bigfile.remaster.patch.002_french_allvo_allplt.000.tiger
ftp://192.168.2.4:2121/mnt/sandbox/pfsmnt/CUSA10872-app0-patch0-union/bigfile.remaster.patch.002_german_allvo_allplt.000.tiger
ftp://192.168.2.4:2121/mnt/sandbox/pfsmnt/CUSA10872-app0-patch0-union/bigfile.remaster.patch.002_iberspanish_allvo_allplt.000.tiger
ftp://192.168.2.4:2121/mnt/sandbox/pfsmnt/CUSA10872-app0-patch0-union/bigfile.remaster.patch.002_italian_allvo_allplt.000.tiger
ftp://192.168.2.4:2121/mnt/sandbox/pfsmnt/CUSA10872-app0-patch0-union/bigfile.remaster.patch.002_latamspanish_allvo_allplt.000.tiger
ftp://192.168.2.4:2121/mnt/sandbox/pfsmnt/CUSA10872-app0-patch0-union/bigfile.remaster.patch.002_polish_allvo_allplt.000.tiger
ftp://192.168.2.4:2121/mnt/sandbox/pfsmnt/CUSA10872-app0-patch0-union/bigfile.remaster.patch.002_portuguese_allvo_allplt.000.tiger
ftp://192.168.2.4:2121/mnt/sandbox/pfsmnt/CUSA10872-app0-patch0-union/bigfile.remaster.patch.002_russian_allvo_allplt.000.tiger
ftp://192.168.2.4:2121/mnt/sandbox/pfsmnt/CUSA10872-app0-patch0-union/bigfile.remaster.patch.003.000.nfo
ftp://192.168.2.4:2121/mnt/sandbox/pfsmnt/CUSA10872-app0-patch0-union/bigfile.remaster.patch.003.000.tiger
ftp://192.168.2.4:2121/mnt/sandbox/pfsmnt/CUSA10872-app0-patch0-union/bigfile.remaster.patch.003_alltxt_english_allplt.000.tiger
ftp://192.168.2.4:2121/mnt/sandbox/pfsmnt/CUSA10872-app0-patch0-union/bigfile.remaster.patch.003_alltxt_french_allplt.000.tiger
ftp://192.168.2.4:2121/mnt/sandbox/pfsmnt/CUSA10872-app0-patch0-union/bigfile.remaster.patch.003_alltxt_german_allplt.000.tiger
ftp://192.168.2.4:2121/mnt/sandbox/pfsmnt/CUSA10872-app0-patch0-union/bigfile.remaster.patch.003_alltxt_iberspanish_allplt.000.tiger
ftp://192.168.2.4:2121/mnt/sandbox/pfsmnt/CUSA10872-app0-patch0-union/bigfile.remaster.patch.003_alltxt_italian_allplt.000.tiger
ftp://192.168.2.4:2121/mnt/sandbox/pfsmnt/CUSA10872-app0-patch0-union/bigfile.remaster.patch.003_alltxt_latamspanish_allplt.000.tiger
ftp://192.168.2.4:2121/mnt/sandbox/pfsmnt/CUSA10872-app0-patch0-union/bigfile.remaster.patch.003_alltxt_polish_allplt.000.tiger
ftp://192.168.2.4:2121/mnt/sandbox/pfsmnt/CUSA10872-app0-patch0-union/bigfile.remaster.patch.003_alltxt_portuguese_allplt.000.tiger
ftp://192.168.2.4:2121/mnt/sandbox/pfsmnt/CUSA10872-app0-patch0-union/bigfile.remaster.patch.003_alltxt_russian_allplt.000.tiger
ftp://192.168.2.4:2121/mnt/sandbox/pfsmnt/CUSA10872-app0-patch0-union/bigfile.remaster.patch.003_english_allvo_allplt.000.tiger
ftp://192.168.2.4:2121/mnt/sandbox/pfsmnt/CUSA10872-app0-patch0-union/bigfile.remaster.patch.003_french_allvo_allplt.000.tiger
ftp://192.168.2.4:2121/mnt/sandbox/pfsmnt/CUSA10872-app0-patch0-union/bigfile.remaster.patch.003_german_allvo_allplt.000.tiger
ftp://192.168.2.4:2121/mnt/sandbox/pfsmnt/CUSA10872-app0-patch0-union/bigfile.remaster.patch.003_iberspanish_allvo_allplt.000.tiger
ftp://192.168.2.4:2121/mnt/sandbox/pfsmnt/CUSA10872-app0-patch0-union/bigfile.remaster.patch.003_italian_allvo_allplt.000.tiger
ftp://192.168.2.4:2121/mnt/sandbox/pfsmnt/CUSA10872-app0-patch0-union/bigfile.remaster.patch.003_latamspanish_allvo_allplt.000.tiger
ftp://192.168.2.4:2121/mnt/sandbox/pfsmnt/CUSA10872-app0-patch0-union/bigfile.remaster.patch.003_polish_allvo_allplt.000.tiger
ftp://192.168.2.4:2121/mnt/sandbox/pfsmnt/CUSA10872-app0-patch0-union/bigfile.remaster.patch.003_portuguese_allvo_allplt.000.tiger
ftp://192.168.2.4:2121/mnt/sandbox/pfsmnt/CUSA10872-app0-patch0-union/bigfile.remaster.patch.003_russian_allvo_allplt.000.tiger
ftp://192.168.2.4:2121/mnt/sandbox/pfsmnt/CUSA10872-app0-patch0-union/bigfile_alltxt_english_allplt.000.tiger
ftp://192.168.2.4:2121/mnt/sandbox/pfsmnt/CUSA10872-app0-patch0-union/bigfile_alltxt_french_allplt.000.tiger
ftp://192.168.2.4:2121/mnt/sandbox/pfsmnt/CUSA10872-app0-patch0-union/bigfile_alltxt_german_allplt.000.tiger
ftp://192.168.2.4:2121/mnt/sandbox/pfsmnt/CUSA10872-app0-patch0-union/bigfile_alltxt_iberspanish_allplt.000.tiger
ftp://192.168.2.4:2121/mnt/sandbox/pfsmnt/CUSA10872-app0-patch0-union/bigfile_alltxt_italian_allplt.000.tiger
ftp://192.168.2.4:2121/mnt/sandbox/pfsmnt/CUSA10872-app0-patch0-union/bigfile_alltxt_latamspanish_allplt.000.tiger
ftp://192.168.2.4:2121/mnt/sandbox/pfsmnt/CUSA10872-app0-patch0-union/bigfile_alltxt_polish_allplt.000.tiger
ftp://192.168.2.4:2121/mnt/sandbox/pfsmnt/CUSA10872-app0-patch0-union/bigfile_alltxt_portuguese_allplt.000.tiger
ftp://192.168.2.4:2121/mnt/sandbox/pfsmnt/CUSA10872-app0-patch0-union/bigfile_alltxt_russian_allplt.000.tiger
ftp://192.168.2.4:2121/mnt/sandbox/pfsmnt/CUSA10872-app0-patch0-union/bigfile_english_allvo_allplt.000.tiger
ftp://192.168.2.4:2121/mnt/sandbox/pfsmnt/CUSA10872-app0-patch0-union/bigfile_french_allvo_allplt.000.tiger
ftp://192.168.2.4:2121/mnt/sandbox/pfsmnt/CUSA10872-app0-patch0-union/bigfile_german_allvo_allplt.000.tiger
ftp://192.168.2.4:2121/mnt/sandbox/pfsmnt/CUSA10872-app0-patch0-union/bigfile_iberspanish_allvo_allplt.000.tiger
ftp://192.168.2.4:2121/mnt/sandbox/pfsmnt/CUSA10872-app0-patch0-union/bigfile_italian_allvo_allplt.000.tiger
ftp://192.168.2.4:2121/mnt/sandbox/pfsmnt/CUSA10872-app0-patch0-union/bigfile_latamspanish_allvo_allplt.000.tiger
ftp://192.168.2.4:2121/mnt/sandbox/pfsmnt/CUSA10872-app0-patch0-union/bigfile_polish_allvo_allplt.000.tiger
ftp://192.168.2.4:2121/mnt/sandbox/pfsmnt/CUSA10872-app0-patch0-union/bigfile_portuguese_allvo_allplt.000.tiger
ftp://192.168.2.4:2121/mnt/sandbox/pfsmnt/CUSA10872-app0-patch0-union/bigfile_russian_allvo_allplt.000.tiger
ftp://192.168.2.4:2121/mnt/sandbox/pfsmnt/CUSA10872-app0-patch0-union/eboot.bin
ftp://192.168.2.4:2121/mnt/sandbox/pfsmnt/CUSA10872-app0-patch0-union/game.specmasks.toc
ftp://192.168.2.4:2121/mnt/sandbox/pfsmnt/CUSA10872-app0-patch0-union/remaster.patch.specmasks.toc
ftp://192.168.2.4:2121/mnt/sandbox/pfsmnt/CUSA10872-app0-patch0-union/remaster.specmasks.toc
ftp://192.168.2.4:2121/mnt/sandbox/pfsmnt/CUSA10872-app0-patch0-union/sce_discmap.plt
ftp://192.168.2.4:2121/mnt/sandbox/pfsmnt/CUSA10872-app0-patch0-union/sku.dat

**Comment by hippie68** [comment] 2022-01-01 20:34
The patch could be a remaster patch that has been fully integrated into the app.

**Comment by RoboFox83** [comment] 2022-01-01 21:42
I've dumped this game and version and can confirm it is a remaster.

**Comment by daydreamer33** [comment] 2022-01-22 17:08
Solution:
Dump only app (because remaster)
after that, edit param.sfo.
Dismark Remaster and switch the Versions.
Then you can make an working fpkg.
Its working, but Information about the game will show you a lower number but its still sottr 2.01 ;)

**Comment by hippie68** [comment] 2022-01-22 18:41
I'm not sure if those steps would work for every single app out there. If they do and users can confirm, I could add it to the script as an optional feature.

**Comment by daydreamer33** [comment] 2022-01-22 18:46
IT works, sonic ultimate + Update, sottr + Update 2.01, and 2 more games.

**Comment by hippie68** [comment] 2022-01-29 15:44
In the new script version I have added option --fix-remaster. I don't have a remaster app that I can test, so please report back if this works like it should.

**Comment by Dushku** [comment] 2022-05-16 03:48
> In the new script version I have added option --fix-remaster. I don't have a remaster app that I can test, so please report back if this works like it should.

I can't figure out what I'm doing wrong. Also Shadow of the Tomb Raider, which I'm pleased to see somebody has had success with 2.01. Anyways, here's what I've tried: https://imgur.com/a/8OxpjQV (last command, I tried copying param.sfo into the same directory since I don't know how to path in Linux I guess).

**Comment by Dushku** [comment] 2022-05-16 03:54
> Solution: Dump only app (because remaster) after that, edit param.sfo. Dismark Remaster and switch the Versions. (Master & application) and safe it. Then you can make an working fpkg. Its working, but Information about the game will show you a lower number but its still sottr 2.01 ;)

Could you elaborate please? Using Fake Package Tools 3.87's orbis-pub-sfo.exe, I tried following your instructions and got this: https://imgur.com/a/0uQLLeJ

**Comment by hippie68** [comment] 2022-05-16 05:25
The warning message told you the file's Linux path. For the remaster fix to work, you need to put the program "sfo" into ftpdump's folder, as described here: https://github.com/hippie68/ftpdump#adding-the-program-sfo

If sfo is present while dumping, the fix should be applied automatically.

**Comment by Dushku** [comment] 2022-05-16 14:18
> The warning message told you the file's Linux path. For the remaster fix to work, you need to put the program "sfo" into ftpdump's folder, as described here: https://github.com/hippie68/ftpdump#adding-the-program-sfo
> 
> If sfo is present while dumping, the fix should be applied automatically.

If I understand this correctly, "while dumping" means I will have to dump again and "automatically" means I won't have to type in --fix-remaster or anything like that, correct?

**Comment by Dushku** [comment] 2022-05-16 14:49
> The warning message told you the file's Linux path. For the remaster fix to work, you need to put the program "sfo" into ftpdump's folder, as described here: https://github.com/hippie68/ftpdump#adding-the-program-sfo
> 
> If sfo is present while dumping, the fix should be applied automatically.

I didn't notice, but that's good info for the future! I really appreciate your help.

From the link you provided, I downloaded the for WSL or 64-bit Linux. When I tried the dump again, it said no such file or directory. But you can see it's right there: https://imgur.com/a/fke11t6 What did I do wrong please?

**Comment by hippie68** [comment] 2022-05-16 20:56
Thanks for finding this bug. Please try this updated script version to see if it works now: 
[ftpdump.zip](https://github.com/hippie68/ftpdump/files/8703305/ftpdump.zip)

**Comment by Dushku** [comment] 2022-05-16 22:40
> Thanks for finding this bug. Please try this updated script version to see if it works now: [ftpdump.zip](https://github.com/hippie68/ftpdump/files/8703305/ftpdump.zip)

Confirmed working. I first started trying to dump this game 25 days ago lol. What a journey it's been!

It did throw 40 warnings at the end. However, I think this is because I forgot to delete the dump before dumping it again.

**Comment by hippie68** [comment] 2023-08-01 07:38
Confirmed that update 2.01 is a remaster patch. It seems the game was dumped successfully with the patch merged into the base game.

> It did throw 40 warnings at the end. However, I think this is because I forgot to delete the dump before dumping it again.

Yes, that should be normal if some files that already exist are skipped.

**Closed** 2023-08-01 07:39 UTC
